package com.opsguard.incident;

public enum TimelineEventType {

    INCIDENT_CREATED,

    INCIDENT_ACKNOWLEDGED,
    INVESTIGATION_STARTED,
    INCIDENT_MITIGATED,
    MONITORING_STARTED,
    INCIDENT_RESOLVED,
    INCIDENT_CLOSED,

    TEAM_ASSIGNED,
    TEAM_UNASSIGNED,

    USER_ASSIGNED,
    USER_UNASSIGNED
}